import com.lti.designpatter.basedao.BaseDAOImpl;
import com.lti.onetoone.Passport;
import com.lti.onetoone.User;

import java.util.Iterator;

import org.junit.jupiter.api.Test;

public class UserPassportTest {
	
	BaseDAOImpl baseDAO = new BaseDAOImpl(); 
	
	@Test
	void assignExistingPassortToExistingUser() { //3
		
		User user = baseDAO.find(User.class, 11);
		System.out.println("User : "+user.getEmailAddress());
		
		Passport passport = baseDAO.find(Passport.class,12);
		System.out.println("Expirty : "+passport.getExpiryYear());
		
		user.setPassport(passport);
		passport.setUser(user); //setting the FK for the passport table
		
		baseDAO.merge(passport);
	}
	
	/*@Test
	void addUserAlongWithPassport() {
		
		User user = new User();
		user.setUsername("King");
		user.setEmailAddress("King@gmail.com");
		user.setAge(22);
		
		Passport passport = new Passport();
		passport.setIssuedBy("Govt Of India");
		passport.setExpiryYear("2032");
		
		user.setPassport(passport); // assigning the passport to the user
		passport.setUser(user);
		
		baseDAO.merge(user);
		//baseDAO.merge(passport); //persist the user, who is aware where the passport is!!!!
		
	}*/
	
	
	@Test
	void addUser() { //1
		User user = new User();
		//user.setUserId(12); -- be aware, dont set it, its autogenerated
		user.setUsername("janet");
		user.setEmailAddress("janet@gmail.com");
		user.setAge(21);
		baseDAO.persist(user);
	}
	
	@Test
	void addManyUsers() {
		User manyUsers[] =new User[5];
		for (int i=0;i<manyUsers.length;i++) {
			manyUsers[i] = new User(); //construct the object
			manyUsers[i].setUsername("user"+i);
			manyUsers[i].setEmailAddress("user"+i+"@gmail.com");
			manyUsers[i].setAge(21+i);
			baseDAO.persist(manyUsers[i]);
		}
	}
	
	@Test
	void addPassport() { //2
		Passport passport = new Passport();
		passport.setIssuedBy("Govt  Of India");
		passport.setExpiryYear("2029");
		baseDAO.persist(passport);
	}
	
	
}
