package com.lti.onetoone;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name="passport2")
/*
 * EMP
 * empno ename job hiredate...sal.. deptno
 * 
 * passno  issued    expiry  uid(FK)
 * 888     GovtIndi  2029    101
 */
public class Passport {

	@Id
	@GeneratedValue //autogenerated
	private int passportNumber;
	
	@Column(name="issued",length=20)
	private String issuedBy;
	
	@Column(name="expityYear")
	private String expiryYear;
	
	@OneToOne
	@JoinColumn(name="uid")
	User user;

	public int getPassportNumber() {
		return passportNumber;
	}

	public void setPassportNumber(int passportNumber) {
		this.passportNumber = passportNumber;
	}

	public String getIssuedBy() {
		return issuedBy;
	}

	public void setIssuedBy(String issuedBy) {
		this.issuedBy = issuedBy;
	}

	public String getExpiryYear() {
		return expiryYear;
	}

	public void setExpiryYear(String expiryYear) {
		this.expiryYear = expiryYear;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	
}
